name: API Documentation
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  create-doc:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: plannr_testing
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: github
          MYSQL_PASSWORD: plannr
          MYSQL_ROOT_PASSWORD: plannr
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.testing-github', '.env');"
    - name: Install Dependencies
      run: |
        composer update
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        php artisan key:generate
        php artisan passport:keys
        php artisan scribe:generate
    - uses: actions/upload-artifact@v2
      with:
        name: openapi-document
        path: public/docs/openapi.yaml
  deploy-doc:
    needs: [create-doc]
    if: ${{ github.event_name == 'push' }}
    name: Deploy API documentation on Bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download openapi json
        uses: actions/download-artifact@v2
        with:
          name: openapi-document
          path: public/docs
      - name: Directory Permissions
        run: chmod -R 777 public/docs
      - uses: bump-sh/github-action@v1
        with:
          doc: plannrcrm
          token: 8cd1a9e31573a13e6870266ad4499a74
          file: public/docs/openapi.yaml
  api-diff:
    needs: [create-doc,deploy-doc]
    if: ${{ github.event_name == 'pull_request' }}
    name: Check API diff on Bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bump-sh/github-action@v1
        with:
          doc: plannrcrm
          token: 8cd1a9e31573a13e6870266ad4499a74
          file: doc/api-documentation.yml
          command: diff
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
